version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
   # sphinx-apidoc -o .readthedocs . .readthedocs --full -A 'Matteo Ferla';
   configuration: .readthedocs/source/conf.py
   builder: html
   fail_on_warning: false

python:
   install:
     - method: pip
       path: .
     - requirements: .readthedocs/requirements.txt